import { Project } from './types';

export const CONTACT_EMAIL = 'oluwapamimoakinjide@gmail.com';

export const PROJECT_DATA: Record<string, Project> = {
    nova: {
        id: "nova",
        title: "NOVA: Agentic AI for Banking",
        subtitle: "Product Manager // RBC Amplify (Patent Pending)",
        tag: "Product Innovation (Patent Pending)",
        context: "Selected for RBC Amplify to lead product strategy for a cross-functional squad tackling complex banking operations.",
        stack: ["Agentic AI", "Product Strategy", "Roadmapping", "Stakeholder Management", "Cross-functional Leadership", "Strategic Communication", "AI/ML Frameworks", "Business Case Development"],
        what: "Conceptualized NOVA, a first-of-its-kind agentic AI concept. Defined the roadmap from MVP to scaled deployment, establishing value proposition and operational mechanics.",
        how: "Identified key administrative bottlenecks and translated them into agent workflows. Built the business case for AI adoption, focusing on operational velocity and scalable advisor efficiency.",
        impact: "Won the $20,000 Prize for 'Best Business Value'. The solution demonstrated forward-looking leadership at the intersection of AI and Operations. Core technology is patent pending.",
        category: ['product', 'tech'],
        year: 2025,
        stats: { strategy: 90, tech: 85, product: 100, leadership: 80 },
        image: "/images/rbc-amplify-team.jpg",
        imageCaption: "Our team celebrating the $20,000 Best Business Value prize at RBC Amplify",
        video: "/NOVA_Cheque.mov"
    },
    wfp: {
        id: "wfp",
        title: "Food Security Measurement — Honours Thesis",
        subtitle: "Lead Researcher // University of Saskatchewan & WFP",
        tag: "Research & Econometrics",
        context: "Co-authored a multi-country empirical study evaluating data quality and cost-efficiency tradeoffs in fragile contexts (Myanmar, Ecuador, Central African Republic).",
        stack: ["Python", "R", "Stata", "Econometrics", "Statistical Modeling", "Research Design", "Data Analysis", "Technical Writing", "Cross-cultural Communication"],
        what: "Quantified survey mode effects (phone vs. face-to-face) on food security measurement using experimental WFP data from Burkina Faso and Ecuador. Found a 67 percentage point cross-country differential in emergency coping strategies.",
        how: "Built predictive models to forecast program demand and executed econometric analysis using rCARI indicators. Navigated complex non-random selection bias to ensure validity across 200+ operational metrics.",
        impact: "Thesis accepted for submission to PacDEV and AAEA. Findings directly inform how humanitarian organizations collect data in fragile contexts — a methodological contribution with real program targeting implications.",
        link: "https://github.com/A-Pamimo/HonorsPaperWFP",
        category: ['strategy', 'tech'],
        year: 2025,
        stats: { strategy: 95, tech: 90, product: 40, leadership: 30 }
    },
    weg: {
        id: "weg",
        title: "World's Edge Group",
        subtitle: "Founder // Advisory Platform",
        tag: "Entrepreneurship",
        context: "Founded an independent economic advisory platform to deliver institutional-grade strategy independent of large firms.",
        stack: ["Economic Valuation", "Impact Modeling", "Brand Systems", "Entrepreneurship", "Client Relations", "Strategic Advisory", "Business Development", "Quantitative Analysis"],
        what: "Designed the operating infrastructure, pricing models, and evaluation frameworks. Created the 'Impact 100' methodology for the Western Canada Economic Forum.",
        how: "Authored comprehensive economic valuation reports and board-ready briefs. Translated technical data into clear strategic narratives for clients like Project HAIRitage.",
        impact: "Established standing evidence of market trust, delivering high-quality impact reports and strategic briefs that rival top-tier consultancies.",
        category: ['strategy', 'tech'],
        year: 2025,
        link: "https://worldsedgegroup.com/",
        stats: { strategy: 100, tech: 60, product: 70, leadership: 100 },
        testimonial: "The final report met our expectations. We really appreciated how detailed it was in direct connection to our goals. It was very clear and efficient. I really appreciated the time taken to explain, in detail, how to present the report to stakeholders.",
        testimonialAuthor: "Executive Director // Regional Arts Organization"
    },
    city: {
        id: "city",
        title: "Municipal Performance System",
        subtitle: "Strategy Intern // City of Saskatoon",
        tag: "Strategy",
        context: "Contributed to a city-wide strategic plan for a municipality of 300,000+ citizens, bridging high-level policy goals with execution readiness.",
        stack: ["Power BI", "SQL", "Strategic Planning", "Variance Analysis", "Data Visualization", "Process Automation", "Stakeholder Reporting", "Financial Analysis"],
        what: "Developed 6 scalable financial dashboards using Power BI and SQL to analyze $1B+ in municipal budget data, translating ambiguous policy into structured performance systems.",
        how: "Performed rigorous variance analysis to identify $1M+ in budget optimizations. Automating monthly reporting processes reduced manual cycle time by 30%.",
        impact: "City leadership gained real-time visibility into strategic priorities. Decisions affecting nearly 300,000 residents were grounded in measurable progress rather than static reports.",
        category: ['strategy', 'tech'],
        year: 2025,
        stats: { strategy: 85, tech: 75, product: 50, leadership: 40 }
    },
    sctc: {
        id: "sctc",
        title: "Saskatoon Summer Players",
        subtitle: "Lead Analyst // WEG (World's Edge Group)",
        tag: "Economic Strategy",
        context: "A local arts organization struggled to justify its funding requests to donors who prioritized 'hard' economic metrics over cultural value. Stepped in to bridge that gap.",
        stack: ["Capital Fundraising", "Economic Impact Analysis", "Reporting", "Stakeholder Communication", "Quantitative Research", "Policy Translation"],
        what: "Authored a comprehensive economic valuation report contributing to an $11M fundraising strategy.",
        how: "Quantified community impact to secure major capital infrastructure. Translated technical findings into clear language for funders and policymakers.",
        impact: "Arts organizations gained credible, quantitative evidence to unlock funding ($11M strategy) and defend cultural infrastructure as economic infrastructure.",
        category: ['tech', 'strategy'],
        year: 2025,
        stats: { strategy: 90, tech: 60, product: 20, leadership: 50 },
        archived: false
    },
    pasa: {
        id: "pasa",
        title: "Pan-African Students Association",
        subtitle: "President // PASA",
        tag: "Leadership",
        context: "Pan-African students were operating in silos, lacking a unified community or professional support network.",
        stack: ["Governance", "Financial Planning", "Community Growth", "Organizational Leadership", "Fundraising", "Partnership Development", "Strategic Planning", "Event Management"],
        what: "Orchestrated a growth strategy that increased annual events from 2 to 10. Led the association to create a durable institutional community.",
        how: "Secured $10K in external funding through strategic financial planning. Positioned PASA as a legitimate stakeholder within the university ecosystem.",
        impact: "Achieved 40% year-over-year membership growth and created lasting professional access. PASA outlives my tenure, the marker of real leadership.",
        category: ['strategy'],
        year: 2023,
        stats: { strategy: 80, tech: 10, product: 60, leadership: 95 },
        archived: true
    },
    ess: {
        id: "ess",
        title: "Economics Students Society",
        subtitle: "Co-Founder & President",
        tag: "Leadership",
        context: "Recognized a gap in professional development and community for Economics students at the university level, deciding to build a solution from scratch.",
        stack: ["Community Building", "Partnerships", "Career Development", "Organizational Design", "Faculty Relations", "Program Development", "Member Engagement"],
        what: "Founded and scaled the first dedicated society for Economics students, filling a critical gap in professional development and academic support.",
        how: "Scaled the organization to 40+ members from ground zero. Built collaborative relationships with faculty and industry partners to launch career development programming.",
        impact: "Created a sustainable institution that provides students with mentorship, industry access, and a sense of belonging within the department.",
        category: ['strategy'],
        year: 2023,
        stats: { strategy: 70, tech: 10, product: 50, leadership: 90 },
        archived: true
    },
    its: {
        id: "its",
        title: "Intelligent Data Operations",
        subtitle: "Technical Product Lead // Interactive Tracking Systems",
        tag: "Data Strategy",
        context: "The company's data collection was manual and expensive. Automated pipelines and improved data availability for decision-making.",
        stack: ["Python", "Flask", "SQL", "Power Automate", "VBA", "Web Scraping", "API Integration"],
        what: "Developed a Python-based web scraping tool and integrated WhatsApp API pipelines for customer communication. Built internal SQL tooling using Flask.",
        how: "Automated Excel reporting with VBA benchmarks and connected marketing flows via Power Automate. By removing manual entry, shifted the focus to analytics.",
        impact: "Reduced manual data collection time by 30% and reporting hours by 50%. Marketing automation engaged 200+ customers, boosting engagement by 40%.",
        category: ['tech', 'product'],
        year: 2024,
        stats: { strategy: 60, tech: 95, product: 70, leadership: 40 }
    },
    uos_research: {
        id: "uos_research",
        title: "Climate Resilience Data",
        subtitle: "Research Assistant // University of Saskatchewan",
        tag: "Quantitative Strategy",
        context: "Understanding climate resilience in sub-Saharan Africa requires precise data. Tasked with cleaning and analyzing massive geo-coded weather datasets.",
        stack: ["Python", "R", "Geo-coding", "Data Visualization", "Resilience Databases", "Government Liaison"],
        what: "Analyzed geo-coded weather data for 3 sub-Saharan African countries and creating visual reports from 150K+ data points. Coordinated with government bodies to build 5 new resilience databases.",
        how: "Used R and Python to script reproducible data cleaning pipelines. Translated raw meteorological data into actionable resilience KPI metrics.",
        impact: "Provided critical evidence on regional climate variations, directly supporting water resource management strategies for vulnerable communities.",
        category: ['tech', 'strategy'],
        year: 2024,
        stats: { strategy: 50, tech: 90, product: 30, leadership: 20 }
    },
    harvest_link: {
        id: "harvest_link",
        title: "HarvestLink Marketplace",
        subtitle: "Product Lead // CoHack Silver Medalist",
        tag: "Product Engineering",
        context: "A hackathon project addressing the supply chain disconnect between local farmers and consumers. Built in 48 hours under high pressure.",
        stack: ["React", "Node.js", "TypeScript", "Tailwind", "Product Management", "Express", "Zustand"],
        what: "Led product direction and contributed to the full-stack development of a two-sided marketplace with secure PIN verification and real-time order tracking.",
        how: "Managed scope to ensure MVP delivery, architecting the farmer/customer separation and implementing the secure pickup workflow.",
        impact: "Won 2nd Place at CoHack. Delivered a functional full-stack application with Auth, Dashboard, and Order Management systems in a single weekend.",
        link: "https://github.com/hxdxri/CoHack",
        category: ['tech', 'product'],
        year: 2025,
        stats: { strategy: 80, tech: 85, product: 90, leadership: 85 }
    },
    tt_migrate: {
        id: "tt_migrate",
        title: "Model Migration Sandbox",
        subtitle: "Builder // Tenstorrent Ecosystem",
        tag: "Developer Tooling",
        context: "Tenstorrent is building AI hardware that rivals NVIDIA, but the developer tooling for migrating models onto their chips is largely nonexistent. Built the tooling myself.",
        stack: ["React", "FastAPI", "Python", "LLM-agnostic APIs", "Hardware ML", "Product Design", "Technical Writing"],
        what: "Designed and built a full-stack developer sandbox for migrating AI models to Tenstorrent hardware, covering a 24-operation compatibility matrix.",
        how: "Architected a React frontend paired with a FastAPI backend, with an LLM-agnostic layer so the tool works regardless of which model is being migrated.",
        impact: "A production-ready PRD and working prototype positioning WEG at the frontier of AI hardware tooling — an ecosystem with almost no developer-facing products yet.",
        link: "https://github.com/A-Pamimo/tt-migrate",
        category: ['tech', 'product'],
        year: 2025,
        stats: { strategy: 70, tech: 95, product: 90, leadership: 50 },
    },
    macro_monitor: {
        id: "macro_monitor",
        title: "MacroMonitor",
        subtitle: "Builder // Self-initiated",
        tag: "Economic Tooling",
        context: "Government economic data in Canada has a 3-6 month publication lag. Built a real-time tracker that pulls from live sources instead.",
        stack: ["Next.js", "TypeScript", "Data APIs", "Economic Analysis", "Product Design"],
        what: "A real-time Canadian macroeconomic dashboard that aggregates live indicators — inflation, employment, GDP proxies — into a single readable interface.",
        how: "Frustrated by the lag in official data, designed and shipped the tool independently. Prioritized clean visualization over data volume.",
        impact: "A self-initiated product with a real user problem at its core — the kind of thing that only gets built when someone cares enough to build it.",
        link: "https://github.com/A-Pamimo/MacroMonitor",
        category: ['tech', 'product'],
        year: 2025,
        stats: { strategy: 80, tech: 85, product: 85, leadership: 30 },
    },
    impact100: {
        id: "impact100",
        title: "IMPACT 100 — Western Canada",
        subtitle: "Lead Analyst // World's Edge Group x WCEF",
        tag: "Economic Research",
        context: "The Western Canada Economic Forum needed a rigorous, defensible ranking of the region's top companies. No such index existed.",
        stack: ["Economic Modeling", "LaTeX", "Data Verification", "Composite Indexing", "Client Management"],
        what: "Built the IMPACT 100 — a ranked index of the top 100 Western Canadian companies using a 60/40 revenue-to-employment composite methodology.",
        how: "Designed the scoring methodology, sourced and verified data across 100 companies, and produced a publication-grade LaTeX report for the client.",
        impact: "$708.9B in total revenues and 689,800 employees represented. First edition of what WCEF intends to publish annually.",
        category: ['strategy'],
        year: 2025,
        stats: { strategy: 95, tech: 50, product: 60, leadership: 70 },
    }
};