import { Project } from './types';

export const CONTACT_EMAIL = 'oluwapamimoakinjide@gmail.com';

export const PROJECT_DATA: Record<string, Project> = {
    xuexi: {
        id: "xuexi",
        title: "xuexi (学习)",
        subtitle: "Product & Builder // Self-initiated",
        tag: "Product · Mobile",
        featured: true,
        status: 'shipped',
        year: 2026,
        category: ['product', 'tech'],
        stack: ["React Native", "Expo", "TypeScript", "SQLite", "FSRS (ts-fsrs)", "Zustand", "Product Design"],
        link: "https://github.com/A-Pamimo",
        context: "A Mandarin-learning app for iOS and web that points the reward loops of doomscrolling at scientifically-backed language acquisition — built offline-first for learners travelling in mainland China.",
        what: "xuexi — an offline-first Mandarin app that turns comprehensible input, FSRS spaced repetition and tone training into a game.",
        how: "One React Native + Expo codebase for iOS and web; bundled content and audio for zero-network use; an FSRS review loop, an i+1 swipe feed, and a multi-speaker Tone Dojo.",
        impact: "Shipped through MVP milestones M1–M5 with a verified sub-10-second cold start to a completable action and tested learning invariants (an 85% known-word floor, ≥3 tone voices per drill).",
        case: {
            problem: {
                statement: "Language learners quit before fluency. The tools that keep you coming back (streak-driven apps) optimize engagement over acquisition, while the methods that actually build comprehension — comprehensible input, spaced repetition, tone training — feel like homework. And the user I built for learns Mandarin while travelling in mainland China, where flaky networks and blocked Western services make most apps unusable exactly when they're needed.",
                users: "Self-directed Mandarin learners — especially ones who travel in mainland China and can't rely on the network or Western services.",
                validation: "Grounded in language-acquisition research (Krashen's comprehensible input, FSRS spaced repetition, high-variability phonetic tone training) and my own experience learning Mandarin — the offline-in-China constraint came directly from that experience, not a guess.",
                successMetric: "A learner can open the app with zero network and reach a genuinely comprehensible, completable action in seconds — never a menu.",
            },
            decision: {
                options: ["Engagement-first (streaks/gamification, thin on method)", "Method-first (rigorous SRS/CI, low retention)"],
                chosen: "Borrow the engagement mechanics, point them at the rigorous method, and make offline-first a hard constraint",
                rationale: "I borrowed the reward mechanics of doomscrolling and mobile games — variable rewards, an infinite feed, streaks, combos, instant haptic and audio feedback — and pointed every one of them at scientifically-backed learning: i+1 comprehensible input, FSRS review, and multi-speaker tone training. Offline-first was treated as a product requirement, not a nice-to-have, because of who the user is.",
                tradeoff: "To guarantee it works fully offline on both iOS and web, I deliberately avoided the expo-sqlite web (wasm) path: immutable content ships as a bundled snapshot and mutable progress lives in memory behind a platform adapter (file-system on native, localStorage on web). That costs bundle size and a build-time content/audio pipeline, but it buys an identical, zero-network experience everywhere. I also cut hard — handwriting/speech recognition, social features, accounts/cloud sync, and an AI chat tutor are all explicitly out of the MVP — to protect the core loop.",
            },
            shipped: {
                summary: "An offline-first Mandarin app (React Native + Expo, one codebase for iOS and web) delivered across five MVP milestones: an FSRS review loop, a Tone Dojo (rapid-fire multi-speaker tone ID with contour drawing, combos and haptics), a swipe feed that only ever serves i+1 comprehensible sentences with tap-to-gloss, and a full gamification layer (XP/levels, variable rewards, streak integrity, weekly recap). Onboarding gates first launch and bootstraps a known-word base so the feed is comprehensible from sentence one.",
                scope: [
                    "FSRS spaced-repetition engine (ts-fsrs), unit-tested",
                    "Tone Dojo — ≥3 distinct speaker voices per tone",
                    "i+1 swipe feed with an 85% known-word floor",
                    "Gamification: XP, variable rewards, streak integrity",
                    "Offline seed + multi-speaker audio pipeline (Qwen3-TTS)",
                ],
            },
            result: {
                metric: "Cold web launch reaches a completable action in under 10s — measured ~0.3s — with zero JS errors",
                metricType: 'usability',
                evidence: "Verified by an automated headless smoke test (onboarding → dojo → tabs). Tested invariants also hold: the feed never serves a sentence below the 85% known-word floor, and every tone drill uses ≥3 distinct speaker voices.",
            },
            reflection: {
                gotWrong: "The offline-first bet — bundling all content and audio — makes the install heavier and means new content requires an app rebuild rather than an over-the-air update. I optimized hard for the travelling-in-China user; if real usage shows content freshness matters more than I've assumed, that tradeoff needs revisiting.",
                next: "M6 polish (reanimated transitions, richer sound design), then TestFlight and optional cloud sync (M7), and swapping the generated i+1 sentences for real Tatoeba ingestion once network egress allows.",
            },
        },
    },
    sangyin: {
        id: "sangyin",
        title: "Sangyin (聲音)",
        subtitle: "Product & Builder // Open source",
        tag: "Product · Cross-platform",
        featured: true,
        status: 'shipped',
        year: 2026,
        category: ['product', 'tech'],
        stack: ["FastAPI", "Python", "Expo / React Native", "TypeScript", "Kokoro-82M TTS", "NDJSON streaming", "DigitalOcean / Modal / R2"],
        links: [
            { label: "Open the app", url: "https://sangyin-web-m5khb.ondigitalocean.app" },
            { label: "Backend API", url: "https://sangyin-backend-inwls.ondigitalocean.app" },
        ],
        context: "A free, open-source audio reader that reads your documents aloud with open-source neural TTS — no paid APIs, no subscriptions — across web, desktop, iOS and Android.",
        what: "Sangyin — an open-source, self-hostable audio reader that streams natural neural TTS to any device.",
        how: "A thin Expo client points at a configurable FastAPI backend that parses documents and streams synthesized audio sentence-by-sentence; the TTS model sits behind a swappable interface (Kokoro-82M by default).",
        impact: "Shipped live (hosted web app + always-on backend) with a one-command self-host path; supports PDF/EPUB/DOCX/URL input, sentence highlighting synced to playback, variable speed, and offline mobile playback.",
        case: {
            problem: {
                statement: "Good neural text-to-speech is finally natural enough to listen to for hours — but the best models are too heavy to run on a phone, and the convenient options are paid APIs behind subscriptions. So people who just want their documents read aloud either pay per use or settle for robotic on-device voices.",
                users: "People who'd rather listen than read — commuters, people with visual or reading differences, anyone working through long PDFs, EPUBs and articles — who don't want a subscription or their text sent to a paid API.",
                validation: "The constraint is technical and real: quality open TTS models (Kokoro-82M, Chatterbox) need more compute than a phone has, which is exactly why paid cloud TTS exists. The missing option was a free, self-hostable reader that still runs everywhere.",
                successMetric: "Open the app on any phone or browser, import a document, press play — nothing to install, nothing to pay, and it can run entirely on hardware you control.",
            },
            decision: {
                options: ["On-device only (private, but robotic/limited voices)", "Paid cloud API (natural, but subscription + your text leaves your control)", "Client–server, self-hostable"],
                chosen: "Split the product: a thin cross-platform client + a self-hostable synthesis backend",
                rationale: "Rather than compromise on voice quality to fit a phone, I split the product: a thin cross-platform client (one Expo codebase for web, desktop, iOS and Android) that points at a configurable backend URL, and a self-hostable FastAPI server that does the parsing and speech synthesis. TTS sits behind a tiny swappable interface so the model (Kokoro by default, Chatterbox for a more natural GPU voice) can change without touching the client, API or parser.",
                tradeoff: "The client–server split is the whole bet: it costs users a backend to point at — mitigated with a hosted demo and a one-command deploy — but in exchange the app gets genuinely good neural voices on any device and stays free and self-hostable. I also chose to stream synthesis sentence-by-sentence (NDJSON) so playback starts after the first sentence instead of waiting for a whole document, trading a more complex streaming protocol for a fast time-to-first-audio.",
            },
            shipped: {
                summary: "Sangyin — a free, open-source audio reader that runs on web, desktop, iOS and Android from a single client, backed by a self-hostable Python/FastAPI server. It parses PDF, EPUB, DOCX, plain text, pasted text and article URLs, then streams synthesized audio with sentence highlighting synced to playback, 0.5×–2× speed control, a document library, resume-where-you-left-off, and offline playback on mobile.",
                scope: [
                    "Cross-platform Expo client (web / desktop / iOS / Android)",
                    "FastAPI backend: document parsing + TTS",
                    "Sentence-by-sentence NDJSON streaming (fast first audio)",
                    "Swappable TTS engine (Kokoro / Chatterbox)",
                    "Hosted demo + one-command cloud deploy",
                ],
            },
            result: {
                metric: "Shipped and live — a hosted web build + always-on backend anyone can open, plus a one-command self-host path",
                metricType: 'product',
                evidence: "Live hosted app and API on DigitalOcean; cross-platform setup scripts (macOS/Linux/Windows) that stand up the backend and stream first audio locally; deploy specs for the API, web app, a serverless GPU voice (Modal) and R2 storage.",
            },
            reflection: {
                gotWrong: "The client–server architecture is the right call for voice quality, but it's a real onboarding tax — 'point the app at a backend' is a concept most readers shouldn't have to hold. The hosted demo hides it, but the self-host story still asks a lot (Python, espeak-ng, a model download).",
                next: "Smooth the self-host path further (a packaged, closer-to-one-click backend), and lean on the swappable-engine interface to add more natural voices without touching the client.",
            },
        },
    },
    macro_monitor: {
        id: "macro_monitor",
        title: "MacroMonitor",
        subtitle: "Builder // Self-initiated",
        tag: "Economic Tooling",
        status: 'prototype',
        context: "Government economic data in Canada has a 3-6 month publication lag. Built a real-time tracker that pulls from live sources instead.",
        stack: ["Next.js", "TypeScript", "Data APIs", "Economic Analysis", "Product Design"],
        what: "A real-time Canadian macroeconomic dashboard that aggregates live indicators — inflation, employment, GDP proxies — into a single readable interface.",
        how: "Frustrated by the lag in official data, designed and shipped the tool independently. Prioritized clean visualization over data volume so the median user gets a fast read, not an exhaustive one.",
        impact: "Self-initiated and shipped as a working tool — early-stage and not yet instrumented for usage. The point was the real-time gap in how official data is published, and closing it.",
        link: "https://github.com/A-Pamimo/MacroMonitor",
        category: ['tech', 'product'],
        year: 2025,
    },
    tt_migrate: {
        id: "tt_migrate",
        title: "Model Migration Sandbox",
        subtitle: "Builder // Tenstorrent Ecosystem",
        tag: "Developer Tooling",
        status: 'prototype',
        context: "Tenstorrent is building AI hardware that rivals NVIDIA, but the developer tooling for migrating models onto their chips is largely nonexistent. Built the tooling myself.",
        stack: ["React", "FastAPI", "Python", "LLM-agnostic APIs", "Hardware ML", "Product Design", "Technical Writing"],
        what: "Designed and built a full-stack developer sandbox for migrating AI models to Tenstorrent hardware, covering a 24-operation compatibility matrix.",
        how: "Architected a React frontend paired with a FastAPI backend, with an LLM-agnostic layer so the tool works regardless of which model is being migrated.",
        impact: "A production-ready PRD and working prototype for an ecosystem with almost no developer-facing products yet.",
        link: "https://github.com/A-Pamimo/tt-migrate",
        category: ['tech', 'product'],
        year: 2025,
    },
    harvest_link: {
        id: "harvest_link",
        title: "HarvestLink Marketplace",
        subtitle: "Product Lead // CoHack Silver Medalist",
        tag: "Product Engineering",
        status: 'prototype',
        context: "A hackathon project addressing the supply chain disconnect between local farmers and consumers. Built in 48 hours under high pressure.",
        stack: ["React", "Node.js", "TypeScript", "Tailwind", "Product Management", "Express", "Zustand"],
        what: "Led product direction and contributed to the full-stack development of a two-sided marketplace with secure PIN verification and real-time order tracking.",
        how: "Managed scope to ensure MVP delivery, architecting the farmer/customer separation and implementing the secure pickup workflow.",
        impact: "Won 2nd Place at CoHack. Delivered a functional full-stack application with Auth, Dashboard, and Order Management systems in a single weekend — a prototype, not a shipped product.",
        link: "https://github.com/hxdxri/CoHack",
        category: ['tech', 'product'],
        year: 2025,
    },
    nova: {
        id: "nova",
        title: "NOVA: Agentic AI for Banking",
        subtitle: "Product Manager // RBC Amplify",
        tag: "Product Innovation (Patent Pending)",
        status: 'concept',
        context: "Selected for RBC Amplify to lead product strategy for a cross-functional squad tackling complex banking operations.",
        stack: ["Agentic AI", "Product Strategy", "Roadmapping", "Stakeholder Management", "Cross-functional Leadership", "Strategic Communication", "AI/ML Frameworks", "Business Case Development"],
        what: "Conceptualized NOVA, a first-of-its-kind agentic AI concept. Defined the roadmap from MVP to scaled deployment, establishing value proposition and operational mechanics.",
        how: "Identified key administrative bottlenecks and translated them into agent workflows. Built the business case for AI adoption, focusing on operational velocity and scalable advisor efficiency.",
        impact: "Won the $20,000 'Best Business Value' prize at RBC Amplify — as a concept and prototype, not a shipped product. Core technology is patent pending.",
        category: ['product', 'tech'],
        year: 2025,
        image: "/images/rbc-amplify-team.jpg",
        imageCaption: "Our team celebrating the $20,000 Best Business Value prize at RBC Amplify",
        video: "/NOVA_Cheque.mov"
    },
    city: {
        id: "city",
        title: "Municipal Performance System",
        subtitle: "Strategy Intern // City of Saskatoon",
        tag: "Strategy",
        status: 'shipped',
        context: "Contributed to a city-wide strategic plan for a municipality of 300,000+ citizens, bridging high-level policy goals with execution readiness.",
        stack: ["Power BI", "SQL", "Strategic Planning", "Variance Analysis", "Data Visualization", "Process Automation", "Stakeholder Reporting", "Financial Analysis"],
        what: "Developed 6 scalable financial dashboards using Power BI and SQL to analyze $1B+ in municipal budget data, translating ambiguous policy into structured performance systems.",
        how: "Performed rigorous variance analysis to identify $1M+ in budget optimizations. Automating monthly reporting processes reduced manual cycle time by 30%.",
        impact: "City leadership gained real-time visibility into strategic priorities. Decisions affecting nearly 300,000 residents were grounded in measurable progress rather than static reports.",
        category: ['strategy', 'tech'],
        year: 2025,
    },
    wfp: {
        id: "wfp",
        title: "Food Security Measurement — Honours Thesis",
        subtitle: "Lead Researcher // University of Saskatchewan & WFP",
        tag: "Research & Econometrics",
        status: 'research',
        context: "Co-authored a multi-country empirical study evaluating data quality and cost-efficiency tradeoffs in fragile contexts (Myanmar, Ecuador, Central African Republic).",
        stack: ["Python", "R", "Stata", "Econometrics", "Statistical Modeling", "Research Design", "Data Analysis", "Technical Writing", "Cross-cultural Communication"],
        what: "Quantified survey mode effects (phone vs. face-to-face) on food security measurement using experimental WFP data from Burkina Faso and Ecuador. Found a 67 percentage point cross-country differential in emergency coping strategies.",
        how: "Built predictive models to forecast program demand and executed econometric analysis using rCARI indicators. Navigated complex non-random selection bias to ensure validity across 200+ operational metrics.",
        impact: "Thesis accepted for submission to PacDEV and AAEA. Findings directly inform how humanitarian organizations collect data in fragile contexts — a methodological contribution with real program targeting implications.",
        link: "https://github.com/A-Pamimo/HonorsPaperWFP",
        category: ['strategy', 'tech'],
        year: 2025,
    },
    impact100: {
        id: "impact100",
        title: "IMPACT 100 — Western Canada",
        subtitle: "Lead Analyst // World's Edge Group x WCEF",
        tag: "Economic Research",
        status: 'research',
        context: "The Western Canada Economic Forum needed a rigorous, defensible ranking of the region's top companies. No such index existed.",
        stack: ["Economic Modeling", "LaTeX", "Data Verification", "Composite Indexing", "Client Management"],
        what: "Built the IMPACT 100 — a ranked index of the top 100 Western Canadian companies using a 60/40 revenue-to-employment composite methodology.",
        how: "Designed the scoring methodology, sourced and verified data across 100 companies, and produced a publication-grade LaTeX report for the client.",
        impact: "$708.9B in total revenues and 689,800 employees represented. First edition of what WCEF intends to publish annually.",
        category: ['strategy'],
        year: 2025,
    },
    weg: {
        id: "weg",
        title: "World's Edge Group",
        subtitle: "Founder // Advisory Platform",
        tag: "Entrepreneurship",
        status: 'shipped',
        context: "Founded an independent economic advisory platform to deliver institutional-grade strategy independent of large firms.",
        stack: ["Economic Valuation", "Impact Modeling", "Brand Systems", "Entrepreneurship", "Client Relations", "Strategic Advisory", "Business Development", "Quantitative Analysis"],
        what: "Designed the operating infrastructure, pricing models, and evaluation frameworks. Created the 'Impact 100' methodology for the Western Canada Economic Forum.",
        how: "Authored comprehensive economic valuation reports and board-ready briefs. Translated technical data into clear strategic narratives for clients like Project HAIRitage.",
        impact: "Established standing evidence of market trust, delivering high-quality impact reports and strategic briefs that rival top-tier consultancies.",
        category: ['strategy', 'tech'],
        year: 2025,
        link: "https://worldsedgegroup.com/",
        testimonial: "The final report met our expectations. We really appreciated how detailed it was in direct connection to our goals. It was very clear and efficient. I really appreciated the time taken to explain, in detail, how to present the report to stakeholders.",
        testimonialAuthor: "Executive Director // Regional Arts Organization"
    },
    sctc: {
        id: "sctc",
        title: "Saskatoon Summer Players",
        subtitle: "Lead Analyst // WEG (World's Edge Group)",
        tag: "Economic Strategy",
        status: 'research',
        context: "A local arts organization struggled to justify its funding requests to donors who prioritized 'hard' economic metrics over cultural value. Stepped in to bridge that gap.",
        stack: ["Capital Fundraising", "Economic Impact Analysis", "Reporting", "Stakeholder Communication", "Quantitative Research", "Policy Translation"],
        what: "Authored a comprehensive economic valuation report contributing to an $11M fundraising strategy.",
        how: "Quantified community impact to secure major capital infrastructure. Translated technical findings into clear language for funders and policymakers.",
        impact: "Arts organizations gained credible, quantitative evidence to unlock funding ($11M strategy) and defend cultural infrastructure as economic infrastructure.",
        category: ['tech', 'strategy'],
        year: 2025,
        archived: false
    },
    its: {
        id: "its",
        title: "Intelligent Data Operations",
        subtitle: "Technical Product Lead // Interactive Tracking Systems",
        tag: "Data Strategy",
        status: 'shipped',
        context: "The company's data collection was manual and expensive. Automated pipelines and improved data availability for decision-making.",
        stack: ["Python", "Flask", "SQL", "Power Automate", "VBA", "Web Scraping", "API Integration"],
        what: "Developed a Python-based web scraping tool and integrated WhatsApp API pipelines for customer communication. Built internal SQL tooling using Flask.",
        how: "Automated Excel reporting with VBA benchmarks and connected marketing flows via Power Automate. By removing manual entry, shifted the focus to analytics.",
        impact: "Reduced manual data collection time by 30% and reporting hours by 50%. Marketing automation engaged 200+ customers, boosting engagement by 40%.",
        category: ['tech', 'product'],
        year: 2024,
    },
    uos_research: {
        id: "uos_research",
        title: "Climate Resilience Data",
        subtitle: "Research Assistant // University of Saskatchewan",
        tag: "Quantitative Strategy",
        status: 'research',
        context: "Understanding climate resilience in sub-Saharan Africa requires precise data. Tasked with cleaning and analyzing massive geo-coded weather datasets.",
        stack: ["Python", "R", "Geo-coding", "Data Visualization", "Resilience Databases", "Government Liaison"],
        what: "Analyzed geo-coded weather data for 3 sub-Saharan African countries and creating visual reports from 150K+ data points. Coordinated with government bodies to build 5 new resilience databases.",
        how: "Used R and Python to script reproducible data cleaning pipelines. Translated raw meteorological data into actionable resilience KPI metrics.",
        impact: "Provided critical evidence on regional climate variations, directly supporting water resource management strategies for vulnerable communities.",
        category: ['tech', 'strategy'],
        year: 2024,
    },
    pasa: {
        id: "pasa",
        title: "Pan-African Students Association",
        subtitle: "President // PASA",
        tag: "Leadership",
        status: 'archived',
        context: "Pan-African students were operating in silos, lacking a unified community or professional support network.",
        stack: ["Governance", "Financial Planning", "Community Growth", "Organizational Leadership", "Fundraising", "Partnership Development", "Strategic Planning", "Event Management"],
        what: "Orchestrated a growth strategy that increased annual events from 2 to 10. Led the association to create a durable institutional community.",
        how: "Secured $10K in external funding through strategic financial planning. Positioned PASA as a legitimate stakeholder within the university ecosystem.",
        impact: "Achieved 40% year-over-year membership growth and created lasting professional access. PASA outlives my tenure, the marker of real leadership.",
        category: ['strategy'],
        year: 2023,
        archived: true
    },
    ess: {
        id: "ess",
        title: "Economics Students Society",
        subtitle: "Co-Founder & President",
        tag: "Leadership",
        status: 'archived',
        context: "Recognized a gap in professional development and community for Economics students at the university level, deciding to build a solution from scratch.",
        stack: ["Community Building", "Partnerships", "Career Development", "Organizational Design", "Faculty Relations", "Program Development", "Member Engagement"],
        what: "Founded and scaled the first dedicated society for Economics students, filling a critical gap in professional development and academic support.",
        how: "Scaled the organization to 40+ members from ground zero. Built collaborative relationships with faculty and industry partners to launch career development programming.",
        impact: "Created a sustainable institution that provides students with mentorship, industry access, and a sense of belonging within the department.",
        category: ['strategy'],
        year: 2023,
        archived: true
    },
};
