# Wrangler configuration for Cloudflare Pages

name = "pamimosite"
compatibility_date = "2026-01-13"
pages_build_output_dir = "out"
# If you use Pages Functions, uncomment and set functions_dir to the folder
# where your functions live (e.g. "functions").
# functions_dir = "functions"

# Notes:
# - If your account/project differ, update account_id and project_name above.

[[d1_databases]]
binding = "DB" # Available in your Worker on env.DB
database_name = "pamimo-db"
database_id = "ad2bdf6a-a98d-4239-b586-0c14e32a7ef6"